*** Settings ***
Library  SeleniumLibrary


*** Variables ***
#Dados gerais
${URL}                      https://opensource-demo.orangehrmlive.com/
${Browser}                  chrome


#Dados do teste
${FirstName}                     Edward
${MiddleName}                    Sheeran
${LastName}                      555-431
${Username}                      teste@gmail.com
${Password}                      123456
${OtherId}                       123456
${DriversLicenseNumber}          87654321